FROM ubuntu:20.04

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev && \
    apt-get clean

# Copy the Vina binary into the container
COPY vina /usr/local/bin/vina

# Make it executable
RUN chmod +x /usr/local/bin/vina

# Default work directory
WORKDIR /data

# Default command
ENTRYPOINT ["vina"]
